package com.app.weather.bean;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "CITYS".
*/
public class CitysDao extends AbstractDao<Citys, Long> {

    public static final String TABLENAME = "CITYS";

    /**
     * Properties of entity Citys.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property City = new Property(1, String.class, "city", false, "CITY");
        public final static Property Weather = new Property(2, String.class, "weather", false, "WEATHER");
        public final static Property DuMax = new Property(3, String.class, "duMax", false, "DU_MAX");
        public final static Property DuMin = new Property(4, String.class, "duMin", false, "DU_MIN");
    }


    public CitysDao(DaoConfig config) {
        super(config);
    }
    
    public CitysDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"CITYS\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"CITY\" TEXT," + // 1: city
                "\"WEATHER\" TEXT," + // 2: weather
                "\"DU_MAX\" TEXT," + // 3: duMax
                "\"DU_MIN\" TEXT);"); // 4: duMin
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"CITYS\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Citys entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String city = entity.getCity();
        if (city != null) {
            stmt.bindString(2, city);
        }
 
        String weather = entity.getWeather();
        if (weather != null) {
            stmt.bindString(3, weather);
        }
 
        String duMax = entity.getDuMax();
        if (duMax != null) {
            stmt.bindString(4, duMax);
        }
 
        String duMin = entity.getDuMin();
        if (duMin != null) {
            stmt.bindString(5, duMin);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Citys entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String city = entity.getCity();
        if (city != null) {
            stmt.bindString(2, city);
        }
 
        String weather = entity.getWeather();
        if (weather != null) {
            stmt.bindString(3, weather);
        }
 
        String duMax = entity.getDuMax();
        if (duMax != null) {
            stmt.bindString(4, duMax);
        }
 
        String duMin = entity.getDuMin();
        if (duMin != null) {
            stmt.bindString(5, duMin);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public Citys readEntity(Cursor cursor, int offset) {
        Citys entity = new Citys( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // city
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // weather
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // duMax
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4) // duMin
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Citys entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setCity(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setWeather(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setDuMax(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setDuMin(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Citys entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Citys entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Citys entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
