package com.app.weather.bean;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.app.weather.bean.Citys;

import com.app.weather.bean.CitysDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig citysDaoConfig;

    private final CitysDao citysDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        citysDaoConfig = daoConfigMap.get(CitysDao.class).clone();
        citysDaoConfig.initIdentityScope(type);

        citysDao = new CitysDao(citysDaoConfig, this);

        registerDao(Citys.class, citysDao);
    }
    
    public void clear() {
        citysDaoConfig.clearIdentityScope();
    }

    public CitysDao getCitysDao() {
        return citysDao;
    }

}
